---
- hosts: webserver
  become: yes
  tasks:
  - name: update packages and install apache
    apt:
      name: apache2
      state: present
      update_cache: yes
  - name: installing php packages
    apt:
      name: "{{ item }}"
      state: present  
    loop:
     - php
     - libapache2-mod-php 
     - php-mcrypt 
     - php-mysql  
     - php-cli
  - name: restart apache 
    service:
      name: apache2
      enabled: yes
      state:  restarted
  - name: copy info php
    copy:
      src: info.php
      dest: /var/www/html/info.php
